Dante 1.3.0-pre1

diff --git a/dante/bin/socksify.in b/dante/bin/socksify.in
--- a/dante/bin/socksify.in
+++ b/dante/bin/socksify.in
@@ -40,22 +40,37 @@
 # any improvements or extensions that they make and grant Inferno Nettverk A/S
 # the rights to redistribute these changes.
 #
-# $Id: socksify.in,v 1.27.4.1 2010/08/01 15:41:24 karls Exp $
+# $Id: socksify.in,v 1.36 2010/09/22 10:33:52 michaels Exp $
 
 #On systems where a supported preloading mechanism is used, you can
 #do "socksify <program>" and <program> will use socks without having
 #been relinked or recompiled.  This will not work on statically linked
 #binaries.
 
+NOPRELOAD="@NOPRELOAD@"
+if test x"$NOPRELOAD" != x; then
+    echo "socksify: error: dante client not built with preloading support."
+    exit 1
+fi
+
 SOCKSIFY_PRELOAD_LIBS="@SOCKSIFY_PRELOAD_LIBS@"
 
-LIBDIR="${LIBDIR:-@LIBRARY_PREFIX@}"
+SOCKS_LIBDIR="${SOCKS_LIBDIR:-@LIBRARY_PREFIX@}"
+
+if test x`uname` = xDarwin; then
+    #specify full path on darwin
+    FULLPATH="${SOCKS_LIBDIR}/"
+    export DYLD_FORCE_FLAT_NAMESPACE=t
+else
+    unset FULLPATH
+fi
 
 #dlib/Makefile.am libtool flags should produce a predictable library name
-LIBRARY="${SOCKS_LIBRARY-${LIBDIR}/libdsocks.@SOLIB_POSTFIX@}"
+LIBRARY="${SOCKS_LIBRARY:-${FULLPATH}libdsocks.@SOLIB_POSTFIX@}"
 
-if ! test -s "$LIBRARY"; then
-    echo "socksify: missing $LIBRARY. no preload support?" >&2
+if test x"$FULLPATH" != x -a ! -s "$LIBRARY" -o \
+        x"$FULLPATH"  = x -a ! -s "$SOCKS_LIBDIR/$LIBRARY"; then
+    echo "socksify: missing \"$LIBRARY\".  No preload support?" >&2
     exit 1
 fi
 
@@ -65,7 +80,13 @@ PRELOAD_POSTFIX="@PRELOAD_POSTFIX@"
 @PRELOAD_VARIABLE@="${LIBRARY}${SOCKSIFY_PRELOAD_LIBS:+${PRELOAD_SEPERATOR}}${SOCKSIFY_PRELOAD_LIBS}${PRELOAD_POSTFIX:+${PRELOAD_SEPERATOR}}${PRELOAD_POSTFIX}"
 export @PRELOAD_VARIABLE@
 
-LD_LIBRARY_PATH="${LD_LIBRARY_PATH}${LD_LIBRARY_PATH:+:}${LIBDIR}"
+LD_LIBRARY_PATH="${LD_LIBRARY_PATH}${LD_LIBRARY_PATH:+:}${SOCKS_LIBDIR}"
 export LD_LIBRARY_PATH
+
+if test x"@ISA64DIR@" != x; then
+    SOCKS_LIB64DIR="${LIB64DIR:-${SOCKS_LIBDIR}/@ISA64DIR@}"
+    LD_LIBRARY_PATH_64="${LD_LIBRARY_PATH_64}${LD_LIBRARY_PATH_64:+:}$SOCKS_LIB64DIR"
+    export LD_LIBRARY_PATH_64
+fi
 
 exec "$@"
