Dante 1.1.15

diff --git a/dante/configure b/dante/configure
--- a/dante/configure
+++ b/dante/configure
@@ -1517,7 +1517,7 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 version=1.1.15
 #set this to enable prerelease, changes some defaults (debug enabled)
-prerelease="3"
+#prerelease="3"
 if test x$prerelease != x; then
 	prename="-pre$prerelease"
 	TOPEXTRADIST="${TOPEXTRADIST} PRERELEASE"
@@ -24784,153 +24784,6 @@ fi
 rm -f conftest*
 
 
-#expected select behaviour?
-unset nb_select_err
-echo "$as_me:$LINENO: checking for correct select behaviour on unconnected sockets" >&5
-echo $ECHO_N "checking for correct select behaviour on unconnected sockets... $ECHO_C" >&6
-if test "$cross_compiling" = yes; then
-  { { echo "$as_me:$LINENO: error: cannot run test program while cross compiling
-See \`config.log' for more details." >&5
-echo "$as_me: error: cannot run test program while cross compiling
-See \`config.log' for more details." >&2;}
-   { (exit 1); exit 1; }; }
-else
-  cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-
-/*
- * ftp.inet.no:/pub/home/michaels/stuff/unconnectedsocket-select.c
- * $ cc unconnectedsocket-select.c && uname -a && ./a.out
- * Modified by Eric Anderson <anderse@hpl.hp.com>
- */
-
-#include <sys/types.h>
-#include <sys/time.h>
-#include <sys/socket.h>
-#include <netinet/in.h>
-#include <arpa/inet.h>
-
-#include <signal.h>
-#include <stdio.h>
-#include <string.h>
-#include <errno.h>
-#include <unistd.h>
-#include <fcntl.h>
-
-static int
-selectcheck(int s);
-
-int
-main(void)
-{
-        char foo[5];
-	int s, p;
-	struct sigaction act;
-	int res;
-
-	act.sa_handler = SIG_IGN;
-	sigaction(SIGPIPE,&act,NULL);
-	fprintf(stderr, "testing with a normal, unconnected socket:\n");
-	if ((s = socket(AF_INET, SOCK_STREAM, 0)) == -1) {
-		perror("socket()");
-		exit(1);
-	}
-	fprintf(stderr, "  created socket, select() returned %d\n",
-	       selectcheck(s));
-	p = read(s, NULL, 0);
-	fprintf(stderr, "  read() returned %d, errno = %d (%s)\n", p, errno, (strerror(errno)));
-	p = write(s, foo, 5);
-	fprintf(stderr, "  write() returned %d, errno = %d (%s)\n", p, errno, (strerror(errno)));
-
-	fprintf(stderr, "testing with a non-blocking, unconnected socket:\n");
-	if ((s = socket(AF_INET, SOCK_STREAM, 0)) == -1) {
-		perror("socket()");
-		exit(1);
-	}
-	if ((p = fcntl(s, F_GETFL, 0)) == -1
-	    || fcntl(s, F_SETFL, p | O_NONBLOCK) == -1) {
-	        perror("fcntl()");
-	        exit(1);
-	}
-	res = selectcheck(s);
-	fprintf(stderr, "  socket nonblocking, select() returned %d\n", res);
-
-	p = read(s, NULL, 0);
-	fprintf(stderr, "  read() returned %d, errno = %d (%s)\n", p, errno, (strerror(errno)));
-	p = write(s, &foo, 5);
-	fprintf(stderr, "  write() returned %d, errno = %d (%s)\n", p, errno, (strerror(errno)));
-
-	if (res == 0)
-		return 0; /* correct behaviour */
-	else
-		return 1; /* incorrect behaviour */
-}
-
-static int
-selectcheck(s)
-	int s;
-{
-	fd_set rset, wset, xset;
-	struct timeval timeout;
-	int ret,i;
-
-	FD_ZERO(&rset);
-	FD_SET(s, &rset);
-	wset = xset = rset;
-
-	timeout.tv_sec 	= 0;
-	timeout.tv_usec 	= 0;
-
-	errno = 0;
-	ret = select(s + 1, &rset, &wset, &xset, &timeout);
-	if (FD_ISSET(s,&rset)) {
-	    fprintf(stderr, "  socket is readable\n");
-	}
-	if (FD_ISSET(s,&wset)) {
-	    fprintf(stderr, "  socket is writeable\n");
-	}
-	if (FD_ISSET(s,&xset)) {
-	    fprintf(stderr, "  socket has an exception\n");
-	}
-	return ret;
-}
-_ACEOF
-rm -f conftest$ac_exeext
-if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
-  (eval $ac_link) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6
-
-else
-  echo "$as_me: program exited with status $ac_status" >&5
-echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-( exit $ac_status )
-echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-     nb_select_err=t
-fi
-rm -f core *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
-fi
-
-if test x"${nb_select_err}" = xt; then
-   { echo "$as_me:$LINENO: WARNING: operations on nonblocking sockets might fail on this platform" >&5
-echo "$as_me: WARNING: operations on nonblocking sockets might fail on this platform" >&2;}
-fi
-
 
 echo "$as_me:$LINENO: checking whether realloc with a NULL pointer calls malloc" >&5
 echo $ECHO_N "checking whether realloc with a NULL pointer calls malloc... $ECHO_C" >&6
@@ -30404,6 +30257,185 @@ _ACEOF
 
 fi
 
+
+#expected select behaviour?
+unset nb_select_err
+echo "$as_me:$LINENO: checking for expected select behaviour" >&5
+echo $ECHO_N "checking for expected select behaviour... $ECHO_C" >&6
+if test "$cross_compiling" = yes; then
+  { { echo "$as_me:$LINENO: error: cannot run test program while cross compiling
+See \`config.log' for more details." >&5
+echo "$as_me: error: cannot run test program while cross compiling
+See \`config.log' for more details." >&2;}
+   { (exit 1); exit 1; }; }
+else
+  cat >conftest.$ac_ext <<_ACEOF
+
+/*
+ * ftp.inet.no:/pub/home/michaels/stuff/socket-select.c
+ * $ cc socket-select.c && uname -a && ./a.out
+ *
+ * Thanks to Eric Anderson <anderse@hpl.hp.com>.
+ *
+*/
+
+#include <sys/types.h>
+#include <sys/time.h>
+#include <sys/socket.h>
+#include <netinet/in.h>
+#include <arpa/inet.h>
+
+#include <signal.h>
+#include <stdio.h>
+#include <string.h>
+#include <errno.h>
+#include <unistd.h>
+#include <fcntl.h>
+
+#define BLOCKING(b)	(b ? ("blocking") : ("non-blocking"))
+
+static int selectcheck(int s);
+static int dotests(int s, int blocking);
+
+int
+main(void)
+{
+	int s, p;
+	struct sigaction sigact;
+
+	sigemptyset(&sigact.sa_mask);
+	sigact.sa_handler = SIG_IGN;
+	sigact.sa_flags 	= 0;
+	if (sigaction(SIGPIPE, &sigact, NULL) != 0) {
+		perror("sigaction()");
+		exit(1);
+	}
+
+	if ((s = socket(AF_INET, SOCK_STREAM, 0)) == -1) {
+		perror("socket()");
+		exit(1);
+	}
+
+	if ((p = fcntl(s, F_GETFL, 0)) == -1
+	|| fcntl(s, F_SETFL, p | O_NONBLOCK) == -1) {
+		perror("fcntl()");
+	   exit(1);
+	}
+
+	p = dotests(s, 0);
+	close(s);
+
+	return p;
+}
+
+
+static int
+dotests(s, blocking)
+	int s;
+	int blocking;
+{
+	int p, rc;
+	struct sockaddr_in addr;
+
+	fprintf(stderr, "testing with %s, bound, socket:\n", BLOCKING(blocking));
+	bzero(&addr, sizeof(addr));
+	addr.sin_family 		= AF_INET;
+	addr.sin_addr.s_addr = htonl(INADDR_ANY);
+	addr.sin_port			= htons(0);
+
+	/* LINTED pointer casts may be troublesome */
+	if (bind(s, (struct sockaddr *)&addr, sizeof(addr)) != 0) {
+		perror("bind(), running linux?");
+		exit(1);
+	}
+
+	fprintf(stderr, "\tselect() returned %d\n", selectcheck(s));
+	p = read(s, NULL, 0);
+	fprintf(stderr, "\tread() returned %d, errno = %d (%s)\n",
+	p, errno, (strerror(errno)));
+	p = write(s, &s, sizeof(s));
+	fprintf(stderr, "\twrite() returned %d, errno = %d (%s)\n",
+	p, errno, (strerror(errno)));
+
+	fprintf(stderr, "testing with %s, bound, listening, socket:\n", BLOCKING(blocking));
+	if (listen(s, 1) != 0) {
+		perror("listen()");
+		exit(1);
+	}
+	fprintf(stderr, "\tselect() returned %d\n", rc = selectcheck(s));
+	p = read(s, NULL, 0);
+	fprintf(stderr, "\tread() returned %d, errno = %d (%s)\n",
+	p, errno, (strerror(errno)));
+	p = write(s, &s, sizeof(s));
+	fprintf(stderr, "\twrite() returned %d, errno = %d (%s)\n",
+	p, errno, (strerror(errno)));
+
+	return rc;
+}
+
+static int
+selectcheck(s)
+	int s;
+{
+	fd_set rset, wset, xset;
+	struct timeval timeout;
+	int ret;
+
+	FD_ZERO(&rset);
+	FD_SET(s, &rset);
+	wset = xset = rset;
+
+	timeout.tv_sec 	= 0;
+	timeout.tv_usec 	= 0;
+
+	errno = 0;
+	ret = select(s + 1, &rset, &wset, &xset, &timeout);
+
+	if (FD_ISSET(s, &rset))
+	    fprintf(stderr, "\tsocket is readable\n");
+
+	if (FD_ISSET(s, &wset))
+	    fprintf(stderr, "\tsocket is writeable\n");
+
+	if (FD_ISSET(s, &xset))
+	    fprintf(stderr, "\tsocket has an exception pending\n");
+
+	return ret;
+}
+_ACEOF
+rm -f conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+else
+  echo "$as_me: program exited with status $ac_status" >&5
+echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+( exit $ac_status )
+echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+     nb_select_err=t
+fi
+rm -f core *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+fi
+
+if test x"${nb_select_err}" = xt; then
+   { echo "$as_me:$LINENO: WARNING: operations on nonblocking sockets might fail on this platform" >&5
+echo "$as_me: WARNING: operations on nonblocking sockets might fail on this platform" >&2;}
+fi
+
+
 echo "$as_me:$LINENO: checking for object file type" >&5
 echo $ECHO_N "checking for object file type... $ECHO_C" >&6
 
@@ -35023,3 +35055,8 @@ stress the server more, increasing the chances of detecting potential
 problems.
 "
 fi
+
+VINFO=README.latest
+test -s "$VINFO" && cat "$VINFO"
+
+exit 0
